# 应用服务 WEB 访问端口
server:
  port: 9093
# 应用名称
spring:
  application:
    name: spring-boot-kafka-consumer
  kafka:
    #连接的broker
    bootstrap-servers: 192.168.175.131:9093,192.168.175.131:9094,192.168.175.131:9095
    producer:
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      #生产者key采用String作为序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #生产者value采用json作为序列化
      #value-serializer: org.apache.kafka.connect.json.JsonSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    test: topicTest
